services:
  - type: web
    name: mundus-news-digest
    env: python
    runtime: python-3.12.7
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install --only-binary=all --no-compile --prefer-binary -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    scaling:
      minInstances: 0
      maxInstances: 1
    disk:
      name: mundus-storage
      mountPath: /opt/render/project/storage
      sizeGB: 1
